### ISSUE TITLE
Converting sudo, notifications, addons and scripts in GitHub actions

### ISSUE THREAD

**Issue by gusbemacbe** [anapaulagomes/from-travis-to-github-actions#1]
Hello @anapaulagomes !

My full Travis file;

```yml
dist: xenial
sudo: required
language: generic

branches:
    - gusbemacbe
notifications:
  email:
    recipients:
      - gusbemacbe@gmail.com
      
addons:
  apt:
    packages:
      - xmlstarlet

script:
    - make -k test-all
```

I converted into GitHub Actions language:

```yml
name: Travis

on:
  pull_request:
    branches:
    - gusbemacbe
              
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Set up Ubuntu's generic SHell Script language
      - uses: actions/checkout@v1
      - run: echo "Analysing..."

# ...
```

I am not sure how to convert sudo, notifications, addons and script.
